### ISSUE TITLE
Request to the videos

### ISSUE THREAD

**Issue by kim1ng** [yale-nlp/TOMATO#1]
Thanks for great work! Do you plan to release the videos used in the benchmark?

**Comment by TobiasLee** [comment]
Awesome work, would like to try the benchmark. Curious about the video release  as well

**Comment by ziyaosg** [comment]
> Thanks for great work! Do you plan to release the videos used in the benchmark?

> Awesome work, would like to try the benchmark. Curious about the video release as well

Thank you for your interests in this work!

Our videos are available for download through [this link](https://drive.google.com/file/d/1-dNt9bZcp6C3RXuGoAO3EBgWkAHg8NWR/view?usp=drive_link).

Please refer to our updated README for detailed evaluation instructions.
